docs(fields): BelongsToMany updated ->inLine method
lee-to/moonshine-doc pull request #518
Opened 2024-07-08 18:13 UTC by carma100

Обновил русскую и английскую версии документации метода `->inLine()` поля BelongsToMany.

![image](https://github.com/moonshine-software/doc/assets/73887319/edbe0d3e-736f-4e0d-abac-244d7ba18e36)
![image](https://github.com/moonshine-software/doc/assets/73887319/dd6e2c50-284a-4e81-a1fb-ef3edee48f12)

2024-07-08 19:29 UTC, DissNik commented
Спасибо

2024-07-08 19:35 UTC, DissNik requested changes

2024-07-08 19:35 UTC, DissNik commented on resources/views/pages/ru/fields/belongs_to_many.blade.php
> +inLine(string $separator = '', Closure|bool $badge = false, ?Closure $link = null)
в en забыли поправить

2024-07-08 19:38 UTC, carma100 commented on resources/views/pages/ru/fields/belongs_to_many.blade.php
> +inLine(string $separator = '', Closure|bool $badge = false, ?Closure $link = null)
спасибо, поправил

2024-07-08 19:55 UTC, DissNik approved these changes

2024-07-22 08:29 UTC, closed without merging

2024-07-22 09:20 UTC, DissNik commented
А почему вы закрыли пр?

2024-07-22 09:26 UTC, carma100 commented
Начал обновлять документацию по кнопкам и экспорту, но видимо накосячил. Сделаю новый пр с экспортом + ->inLine? или сделать два отдельных пр? Прошу прощения 🙇‍♂️

2024-07-22 09:33 UTC, DissNik commented
как вам удобно. можно одним, можно двумя. если будут вопросы, пишите