[3.x] ru/fields/select.md
lee-to/moonshine-doc pull request #545
Opened 2024-10-04 21:00 UTC by ArtemYurov

нужна ссылка на events и комментарии по ним

2024-10-04 23:13 UTC, JeRabix commented on ru/fields/select.md
> +
@ArtemYurov разделитель между навигацией и контентом нужен `---`
https://github.com/moonshine-software/doc/tree/3.x?tab=readme-ov-file#%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C

2024-10-05 03:37 UTC, DissNik requested changes

2024-10-05 03:37 UTC, DissNik commented on ru/fields/select.md
> +public function fields(): array
предлагаю больше не использовать примеры в конкретных методах, в чате был случай когда такой пример запутал, метода fields в v3 нет

```php
use MoonShine\UI\Fields\Select;

Select::make('Country', 'country_id')
    ->options([
        'value 1' => 'Option Label 1',
        'value 2' => 'Option Label 2'
    ])
    ->default('value 2')
```

2024-10-05 05:05 UTC, ArtemYurov commented on ru/fields/select.md
> +
@DissNik @lee-to в других файлах почти везде отсутствует. обновить?

2024-10-05 05:08 UTC, ArtemYurov commented on ru/fields/select.md
> +public function fields(): array
согласен, и меньше места занимает

2024-10-05 05:23 UTC, DissNik commented on ru/fields/select.md
> +
нужно разместить не после заголовка а после навигации, чтоб потом можно было распарсить

2024-10-05 05:29 UTC, merged